// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_mainscreen
void ui_mainscreen_screen_init(void);
void ui_event_mainscreen(lv_event_t * e);
lv_obj_t * ui_mainscreen;
void ui_event_diseasebutton(lv_event_t * e);
lv_obj_t * ui_diseasebutton;
lv_obj_t * ui_diseasetext;
void ui_event_loginoutbutton(lv_event_t * e);
lv_obj_t * ui_loginoutbutton;
lv_obj_t * ui_loginouttext;
void ui_event_medicineinbutton(lv_event_t * e);
lv_obj_t * ui_medicineinbutton;
lv_obj_t * ui_medicineintext;
void ui_event_medicineoutbutton(lv_event_t * e);
lv_obj_t * ui_medicineoutbutton;
lv_obj_t * ui_medicineouttext;
lv_obj_t * ui_time;
lv_obj_t * ui_fingertext;
lv_obj_t * ui_date;
// CUSTOM VARIABLES

// SCREEN: ui_medicineinpanel
void ui_medicineinpanel_screen_init(void);
void ui_event_medicineinpanel(lv_event_t * e);
lv_obj_t * ui_medicineinpanel;
lv_obj_t * ui_scanhint;
void ui_event_back(lv_event_t * e);
lv_obj_t * ui_back;
lv_obj_t * ui_backtext;
lv_obj_t * ui_Panel1;
void ui_event_Keyboard2(lv_event_t * e);
lv_obj_t * ui_Keyboard2;
void ui_event_times(lv_event_t * e);
lv_obj_t * ui_times;
void ui_event_amount(lv_event_t * e);
lv_obj_t * ui_amount;
lv_obj_t * ui_texttimes;
lv_obj_t * ui_textamount;
// CUSTOM VARIABLES

// SCREEN: ui_medicineoutpanel
void ui_medicineoutpanel_screen_init(void);
void ui_event_medicineoutpanel(lv_event_t * e);
lv_obj_t * ui_medicineoutpanel;
lv_obj_t * ui_outhint;
void ui_event_out1(lv_event_t * e);
lv_obj_t * ui_out1;
lv_obj_t * ui_out1text;
void ui_event_out3(lv_event_t * e);
lv_obj_t * ui_out3;
lv_obj_t * ui_out3text;
void ui_event_out2(lv_event_t * e);
lv_obj_t * ui_out2;
lv_obj_t * ui_out2text;
void ui_event_back2(lv_event_t * e);
lv_obj_t * ui_back2;
lv_obj_t * ui_back2text;
void ui_event_out4(lv_event_t * e);
lv_obj_t * ui_out4;
lv_obj_t * ui_out4text;
void ui_event_out5(lv_event_t * e);
lv_obj_t * ui_out5;
lv_obj_t * ui_out5text;
// CUSTOM VARIABLES

// SCREEN: ui_emotion
void ui_emotion_screen_init(void);
void ui_event_emotion(lv_event_t * e);
lv_obj_t * ui_emotion;
lv_obj_t * ui_smile;
lv_obj_t * ui_sad;
lv_obj_t * ui_question;
lv_obj_t * ui_responsetext;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_mainscreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        update_time(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

void ui_event_diseasebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_emotion, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_emotion_screen_init);
        disease_anl(e);
    }
}

void ui_event_loginoutbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_fingertext, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        read_finger(e);
    }
}

void ui_event_medicineinbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_medicineinpanel, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 100, &ui_medicineinpanel_screen_init);
        read_bar(e);
    }
}

void ui_event_medicineoutbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_medicineoutpanel, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 100, &ui_medicineoutpanel_screen_init);
        medicine_out(e);
    }
}

void ui_event_medicineinpanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

void ui_event_back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_mainscreen_screen_init);
        m_inback(e);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        msg_send(e);
    }
}

void ui_event_times(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_times);
    }
}

void ui_event_amount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_amount);
    }
}

void ui_event_medicineoutpanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

void ui_event_out1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        del_medicine(e);
    }
}

void ui_event_out3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        del_medicine(e);
    }
}

void ui_event_out2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        del_medicine(e);
    }
}

void ui_event_back2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_mainscreen_screen_init);
        m_outback(e);
    }
}

void ui_event_out4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        del_medicine(e);
    }
}

void ui_event_out5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        del_medicine(e);
    }
}

void ui_event_emotion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_mainscreen_screen_init();
    ui_medicineinpanel_screen_init();
    ui_medicineoutpanel_screen_init();
    ui_emotion_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_mainscreen);
}
