// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_mainscreen.h"
#include "screens/ui_medicineinpanel.h"
#include "screens/ui_medicineoutpanel.h"
#include "screens/ui_emotion.h"
#include "screens/ui_settingsscreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_medicine_png);    // assets/medicine.png
LV_IMG_DECLARE(ui_img_smile_png);    // assets/smile.png
LV_IMG_DECLARE(ui_img_sad_png);    // assets/sad.png
LV_IMG_DECLARE(ui_img_question_png);    // assets/question.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png

// FONTS
LV_FONT_DECLARE(ui_font_big);
LV_FONT_DECLARE(ui_font_huge);
LV_FONT_DECLARE(ui_font_midbig);
LV_FONT_DECLARE(ui_font_small);
LV_FONT_DECLARE(ui_font_verybig);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
