// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void update_time(lv_event_t * e);
void touch_event_handler(lv_event_t * e);
void disease_anl(lv_event_t * e);
void read_finger(lv_event_t * e);
void read_bar(lv_event_t * e);
void medicine_out(lv_event_t * e);
void m_inback(lv_event_t * e);
void msg_send(lv_event_t * e);
void del_medicine(lv_event_t * e);
void m_outback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
