// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_EMOTION_H
#define UI_EMOTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_emotion
extern void ui_emotion_screen_init(void);
extern void ui_emotion_screen_destroy(void);
extern void ui_event_emotion(lv_event_t * e);
extern lv_obj_t * ui_emotion;
extern lv_obj_t * ui_smile;
extern lv_obj_t * ui_sad;
extern lv_obj_t * ui_question;
extern lv_obj_t * ui_responsetext;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

