// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_emotion = NULL;
lv_obj_t * ui_smile = NULL;
lv_obj_t * ui_sad = NULL;
lv_obj_t * ui_question = NULL;
lv_obj_t * ui_responsetext = NULL;
lv_obj_t * ui_Spinner1 = NULL;
// event funtions
void ui_event_emotion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

// build funtions

void ui_emotion_screen_init(void)
{
    ui_emotion = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_emotion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_emotion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_emotion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_smile = lv_img_create(ui_emotion);
    lv_img_set_src(ui_smile, &ui_img_smile_png);
    lv_obj_set_width(ui_smile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_smile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_smile, 0);
    lv_obj_set_y(ui_smile, -70);
    lv_obj_set_align(ui_smile, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smile, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sad = lv_img_create(ui_emotion);
    lv_img_set_src(ui_sad, &ui_img_sad_png);
    lv_obj_set_width(ui_sad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sad, 0);
    lv_obj_set_y(ui_sad, -70);
    lv_obj_set_align(ui_sad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sad, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_question = lv_img_create(ui_emotion);
    lv_img_set_src(ui_question, &ui_img_question_png);
    lv_obj_set_width(ui_question, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_question, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_question, 0);
    lv_obj_set_y(ui_question, -70);
    lv_obj_set_align(ui_question, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_question, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_question, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_responsetext = lv_label_create(ui_emotion);
    lv_obj_set_width(ui_responsetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_responsetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_responsetext, 0);
    lv_obj_set_y(ui_responsetext, 60);
    lv_obj_set_align(ui_responsetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_responsetext, "");
    lv_obj_set_style_text_font(ui_responsetext, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_emotion, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 40);
    lv_obj_set_height(ui_Spinner1, 40);
    lv_obj_set_x(ui_Spinner1, -110);
    lv_obj_set_y(ui_Spinner1, 60);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x056AFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_emotion, ui_event_emotion, LV_EVENT_ALL, NULL);

}

void ui_emotion_screen_destroy(void)
{
    if(ui_emotion) lv_obj_del(ui_emotion);

    // NULL screen variables
    ui_emotion = NULL;
    ui_smile = NULL;
    ui_sad = NULL;
    ui_question = NULL;
    ui_responsetext = NULL;
    ui_Spinner1 = NULL;

}
