// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_medicineoutpanel_screen_init(void)
{
    ui_medicineoutpanel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_medicineoutpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_medicineoutpanel, &ui_img_medicine_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_outhint = lv_label_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_outhint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_outhint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_outhint, 0);
    lv_obj_set_y(ui_outhint, -100);
    lv_obj_set_align(ui_outhint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_outhint, "请选择要移除的药物格");
    lv_obj_set_style_text_font(ui_outhint, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_outhint, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_outhint, lv_color_hex(0xC1F8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_outhint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_outhint, lv_color_hex(0x00C1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_outhint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_outhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_outhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_outhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_outhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out1 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_out1, 60);
    lv_obj_set_height(ui_out1, 60);
    lv_obj_set_x(ui_out1, -190);
    lv_obj_set_y(ui_out1, -10);
    lv_obj_set_align(ui_out1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_out1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_out1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_out1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_out1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_out1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_out1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out1text = lv_label_create(ui_out1);
    lv_obj_set_width(ui_out1text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_out1text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_out1text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_out1text, "1");
    lv_obj_set_style_text_font(ui_out1text, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out3 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_out3, 60);
    lv_obj_set_height(ui_out3, 60);
    lv_obj_set_x(ui_out3, 0);
    lv_obj_set_y(ui_out3, -10);
    lv_obj_set_align(ui_out3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_out3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_out3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_out3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_out3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_out3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_out3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out3text = lv_label_create(ui_out3);
    lv_obj_set_width(ui_out3text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_out3text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_out3text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_out3text, "3");
    lv_obj_set_style_text_font(ui_out3text, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out2 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_out2, 60);
    lv_obj_set_height(ui_out2, 60);
    lv_obj_set_x(ui_out2, -95);
    lv_obj_set_y(ui_out2, -10);
    lv_obj_set_align(ui_out2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_out2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_out2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_color(ui_out2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_out2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_out2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_out2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out2text = lv_label_create(ui_out2);
    lv_obj_set_width(ui_out2text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_out2text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_out2text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_out2text, "2");
    lv_obj_set_style_text_font(ui_out2text, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back2 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_back2, 130);
    lv_obj_set_height(ui_back2, 70);
    lv_obj_set_x(ui_back2, 0);
    lv_obj_set_y(ui_back2, 85);
    lv_obj_set_align(ui_back2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_back2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_back2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_back2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_back2, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_back2, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_back2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_back2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_back2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_back2, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_back2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_back2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_back2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_back2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_back2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_back2, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_back2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back2text = lv_label_create(ui_back2);
    lv_obj_set_width(ui_back2text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back2text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_back2text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_back2text, "返回");
    lv_obj_set_style_text_font(ui_back2text, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out4 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_out4, 60);
    lv_obj_set_height(ui_out4, 60);
    lv_obj_set_x(ui_out4, 95);
    lv_obj_set_y(ui_out4, -10);
    lv_obj_set_align(ui_out4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_out4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_out4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_width(ui_out4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_out4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out4text = lv_label_create(ui_out4);
    lv_obj_set_width(ui_out4text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_out4text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_out4text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_out4text, "4");
    lv_obj_set_style_text_font(ui_out4text, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out5 = lv_btn_create(ui_medicineoutpanel);
    lv_obj_set_width(ui_out5, 60);
    lv_obj_set_height(ui_out5, 60);
    lv_obj_set_x(ui_out5, 190);
    lv_obj_set_y(ui_out5, -10);
    lv_obj_set_align(ui_out5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_out5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_out5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_outline_width(ui_out5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_out5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_out5text = lv_label_create(ui_out5);
    lv_obj_set_width(ui_out5text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_out5text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_out5text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_out5text, "5");
    lv_obj_set_style_text_font(ui_out5text, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_out1, ui_event_out1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_out3, ui_event_out3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_out2, ui_event_out2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_back2, ui_event_back2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_out4, ui_event_out4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_out5, ui_event_out5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medicineoutpanel, ui_event_medicineoutpanel, LV_EVENT_ALL, NULL);

}
