// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MEDICINEINPANEL_H
#define UI_MEDICINEINPANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_medicineinpanel
extern void ui_medicineinpanel_screen_init(void);
extern void ui_medicineinpanel_screen_destroy(void);
extern void ui_event_medicineinpanel(lv_event_t * e);
extern lv_obj_t * ui_medicineinpanel;
extern lv_obj_t * ui_scanhint;
extern void ui_event_back(lv_event_t * e);
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_backtext;
extern lv_obj_t * ui_Panel1;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_times(lv_event_t * e);
extern lv_obj_t * ui_times;
extern void ui_event_amount(lv_event_t * e);
extern lv_obj_t * ui_amount;
extern lv_obj_t * ui_texttimes;
extern lv_obj_t * ui_textamount;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

