// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_mainscreen = NULL;
lv_obj_t * ui_diseasebutton = NULL;
lv_obj_t * ui_diseasetext = NULL;
lv_obj_t * ui_loginoutbutton = NULL;
lv_obj_t * ui_loginouttext = NULL;
lv_obj_t * ui_medicineinbutton = NULL;
lv_obj_t * ui_medicineintext = NULL;
lv_obj_t * ui_medicineoutbutton = NULL;
lv_obj_t * ui_medicineouttext = NULL;
lv_obj_t * ui_lockbutton = NULL;
lv_obj_t * ui_unlockbutton = NULL;
lv_obj_t * ui_setbutton = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_fingertext = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_aht = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_starttext = NULL;
lv_obj_t * ui_Bar1 = NULL;
// event funtions
void ui_event_mainscreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        update_time(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

void ui_event_diseasebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_emotion, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_emotion_screen_init);
        disease_anl(e);
    }
}

void ui_event_loginoutbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_fingertext, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_time, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        read_finger(e);
    }
}

void ui_event_medicineinbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_medicineinpanel, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 100, &ui_medicineinpanel_screen_init);
        read_bar(e);
    }
}

void ui_event_medicineoutbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_medicineoutpanel, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 100, &ui_medicineoutpanel_screen_init);
        medicine_out(e);
    }
}

void ui_event_lockbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        force_lock(e);
        _ui_flag_modify(ui_lockbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_unlockbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_unlockbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        force_unlock(e);
        _ui_flag_modify(ui_unlockbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_lockbutton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_setbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_settingsscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_settingsscreen_screen_init);
    }
}

// build funtions

void ui_mainscreen_screen_init(void)
{
    ui_mainscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_mainscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_mainscreen, &ui_img_background_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diseasebutton = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_diseasebutton, 100);
    lv_obj_set_height(ui_diseasebutton, 50);
    lv_obj_set_x(ui_diseasebutton, 180);
    lv_obj_set_y(ui_diseasebutton, 100);
    lv_obj_set_align(ui_diseasebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_diseasebutton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_diseasebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_diseasebutton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_diseasebutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_diseasebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_diseasebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_diseasebutton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_diseasebutton, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_diseasebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_diseasebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_diseasebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_diseasebutton, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_diseasebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_diseasebutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_diseasebutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_diseasebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_diseasebutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_diseasebutton, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_diseasebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diseasetext = lv_label_create(ui_diseasebutton);
    lv_obj_set_width(ui_diseasetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_diseasetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_diseasetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_diseasetext, "病情分析");
    lv_obj_set_style_text_font(ui_diseasetext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginoutbutton = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_loginoutbutton, 100);
    lv_obj_set_height(ui_loginoutbutton, 50);
    lv_obj_set_x(ui_loginoutbutton, -180);
    lv_obj_set_y(ui_loginoutbutton, 100);
    lv_obj_set_align(ui_loginoutbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginoutbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginoutbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_loginoutbutton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_loginoutbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_loginoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_loginoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_loginoutbutton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_loginoutbutton, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_loginoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_loginoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_loginoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_loginoutbutton, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_loginoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_loginoutbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_loginoutbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_loginoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_loginoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_loginoutbutton, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loginoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginouttext = lv_label_create(ui_loginoutbutton);
    lv_obj_set_width(ui_loginouttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loginouttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_loginouttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loginouttext, "身份绑定");
    lv_obj_set_style_text_font(ui_loginouttext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medicineinbutton = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_medicineinbutton, 100);
    lv_obj_set_height(ui_medicineinbutton, 50);
    lv_obj_set_x(ui_medicineinbutton, -60);
    lv_obj_set_y(ui_medicineinbutton, 100);
    lv_obj_set_align(ui_medicineinbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_medicineinbutton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_medicineinbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_medicineinbutton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_medicineinbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_medicineinbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_medicineinbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_medicineinbutton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_medicineinbutton, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_medicineinbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_medicineinbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_medicineinbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_medicineinbutton, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_medicineinbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_medicineinbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_medicineinbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_medicineinbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_medicineinbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_medicineinbutton, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_medicineinbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medicineintext = lv_label_create(ui_medicineinbutton);
    lv_obj_set_width(ui_medicineintext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_medicineintext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_medicineintext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_medicineintext, "药物录入");
    lv_obj_set_style_text_font(ui_medicineintext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medicineoutbutton = lv_btn_create(ui_mainscreen);
    lv_obj_set_width(ui_medicineoutbutton, 100);
    lv_obj_set_height(ui_medicineoutbutton, 50);
    lv_obj_set_x(ui_medicineoutbutton, 60);
    lv_obj_set_y(ui_medicineoutbutton, 100);
    lv_obj_set_align(ui_medicineoutbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_medicineoutbutton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_medicineoutbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_medicineoutbutton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_medicineoutbutton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_medicineoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_medicineoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_medicineoutbutton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_medicineoutbutton, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_medicineoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_medicineoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_medicineoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_medicineoutbutton, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_medicineoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_medicineoutbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_medicineoutbutton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_medicineoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_medicineoutbutton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_medicineoutbutton, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_medicineoutbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medicineouttext = lv_label_create(ui_medicineoutbutton);
    lv_obj_set_width(ui_medicineouttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_medicineouttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_medicineouttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_medicineouttext, "药物移除");
    lv_obj_set_style_text_font(ui_medicineouttext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lockbutton = lv_imgbtn_create(ui_mainscreen);
    lv_imgbtn_set_src(ui_lockbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lock_png, NULL);
    lv_imgbtn_set_src(ui_lockbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lock_png, NULL);
    lv_obj_set_width(ui_lockbutton, 50);
    lv_obj_set_height(ui_lockbutton, 50);
    lv_obj_set_x(ui_lockbutton, -200);
    lv_obj_set_y(ui_lockbutton, 30);
    lv_obj_set_align(ui_lockbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lockbutton, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_blend_mode(ui_lockbutton, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_lockbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_unlockbutton = lv_imgbtn_create(ui_mainscreen);
    lv_imgbtn_set_src(ui_unlockbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_unlock_png, NULL);
    lv_imgbtn_set_src(ui_unlockbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_unlock_png, NULL);
    lv_obj_set_width(ui_unlockbutton, 50);
    lv_obj_set_height(ui_unlockbutton, 50);
    lv_obj_set_x(ui_unlockbutton, -200);
    lv_obj_set_y(ui_unlockbutton, 30);
    lv_obj_set_align(ui_unlockbutton, LV_ALIGN_CENTER);

    ui_setbutton = lv_imgbtn_create(ui_mainscreen);
    lv_imgbtn_set_src(ui_setbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_png, NULL);
    lv_imgbtn_set_src(ui_setbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_png, NULL);
    lv_obj_set_width(ui_setbutton, 50);
    lv_obj_set_height(ui_setbutton, 50);
    lv_obj_set_x(ui_setbutton, 200);
    lv_obj_set_y(ui_setbutton, 30);
    lv_obj_set_align(ui_setbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_setbutton, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_setbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_time = lv_label_create(ui_mainscreen);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, 0);
    lv_obj_set_y(ui_time, -80);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "");
    lv_obj_set_style_text_font(ui_time, &ui_font_huge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fingertext = lv_label_create(ui_mainscreen);
    lv_obj_set_width(ui_fingertext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fingertext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fingertext, 0);
    lv_obj_set_y(ui_fingertext, -60);
    lv_obj_set_align(ui_fingertext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fingertext, "请将手指放在识别处");
    lv_obj_add_flag(ui_fingertext, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_fingertext, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_mainscreen);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 0);
    lv_obj_set_y(ui_date, -10);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "");
    lv_obj_set_style_text_font(ui_date, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_aht = lv_label_create(ui_mainscreen);
    lv_obj_set_width(ui_aht, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_aht, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_aht, 0);
    lv_obj_set_y(ui_aht, 30);
    lv_obj_set_align(ui_aht, LV_ALIGN_CENTER);
    lv_label_set_text(ui_aht, "");
    lv_obj_set_style_text_font(ui_aht, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_mainscreen);
    lv_obj_set_width(ui_Panel2, 480);
    lv_obj_set_height(ui_Panel2, 272);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_starttext = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_starttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_starttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_starttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_starttext, "正在启动...");
    lv_obj_set_style_text_font(ui_starttext, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Panel2);
    lv_obj_set_width(ui_Bar1, 300);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 70);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_diseasebutton, ui_event_diseasebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loginoutbutton, ui_event_loginoutbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medicineinbutton, ui_event_medicineinbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medicineoutbutton, ui_event_medicineoutbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lockbutton, ui_event_lockbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_unlockbutton, ui_event_unlockbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setbutton, ui_event_setbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainscreen, ui_event_mainscreen, LV_EVENT_ALL, NULL);

}

void ui_mainscreen_screen_destroy(void)
{
    if(ui_mainscreen) lv_obj_del(ui_mainscreen);

    // NULL screen variables
    ui_mainscreen = NULL;
    ui_diseasebutton = NULL;
    ui_diseasetext = NULL;
    ui_loginoutbutton = NULL;
    ui_loginouttext = NULL;
    ui_medicineinbutton = NULL;
    ui_medicineintext = NULL;
    ui_medicineoutbutton = NULL;
    ui_medicineouttext = NULL;
    ui_lockbutton = NULL;
    ui_unlockbutton = NULL;
    ui_setbutton = NULL;
    ui_time = NULL;
    ui_fingertext = NULL;
    ui_date = NULL;
    ui_aht = NULL;
    ui_Panel2 = NULL;
    ui_starttext = NULL;
    ui_Bar1 = NULL;

}
