// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MEDICINEOUTPANEL_H
#define UI_MEDICINEOUTPANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_medicineoutpanel
extern void ui_medicineoutpanel_screen_init(void);
extern void ui_medicineoutpanel_screen_destroy(void);
extern void ui_event_medicineoutpanel(lv_event_t * e);
extern lv_obj_t * ui_medicineoutpanel;
extern lv_obj_t * ui_outhint;
extern void ui_event_out1(lv_event_t * e);
extern lv_obj_t * ui_out1;
extern lv_obj_t * ui_out1text;
extern void ui_event_out3(lv_event_t * e);
extern lv_obj_t * ui_out3;
extern lv_obj_t * ui_out3text;
extern void ui_event_out2(lv_event_t * e);
extern lv_obj_t * ui_out2;
extern lv_obj_t * ui_out2text;
extern void ui_event_back2(lv_event_t * e);
extern lv_obj_t * ui_back2;
extern lv_obj_t * ui_back2text;
extern void ui_event_out4(lv_event_t * e);
extern lv_obj_t * ui_out4;
extern lv_obj_t * ui_out4text;
extern void ui_event_out5(lv_event_t * e);
extern lv_obj_t * ui_out5;
extern lv_obj_t * ui_out5text;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

