// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainscreen
extern void ui_mainscreen_screen_init(void);
extern void ui_mainscreen_screen_destroy(void);
extern void ui_event_mainscreen(lv_event_t * e);
extern lv_obj_t * ui_mainscreen;
extern void ui_event_diseasebutton(lv_event_t * e);
extern lv_obj_t * ui_diseasebutton;
extern lv_obj_t * ui_diseasetext;
extern void ui_event_loginoutbutton(lv_event_t * e);
extern lv_obj_t * ui_loginoutbutton;
extern lv_obj_t * ui_loginouttext;
extern void ui_event_medicineinbutton(lv_event_t * e);
extern lv_obj_t * ui_medicineinbutton;
extern lv_obj_t * ui_medicineintext;
extern void ui_event_medicineoutbutton(lv_event_t * e);
extern lv_obj_t * ui_medicineoutbutton;
extern lv_obj_t * ui_medicineouttext;
extern void ui_event_lockbutton(lv_event_t * e);
extern lv_obj_t * ui_lockbutton;
extern void ui_event_setbutton(lv_event_t * e);
extern lv_obj_t * ui_setbutton;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_fingertext;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_aht;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_starttext;
extern lv_obj_t * ui_Bar1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

