// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_medicineinpanel_screen_init(void)
{
    ui_medicineinpanel = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_medicineinpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_medicineinpanel, &ui_img_medicine_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scanhint = lv_label_create(ui_medicineinpanel);
    lv_obj_set_width(ui_scanhint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scanhint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scanhint, 0);
    lv_obj_set_y(ui_scanhint, -30);
    lv_obj_set_align(ui_scanhint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scanhint, "请扫描药物条码");
    lv_obj_set_style_text_font(ui_scanhint, &ui_font_verybig, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_scanhint, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_scanhint, lv_color_hex(0xC1F8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scanhint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scanhint, lv_color_hex(0x00C1FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scanhint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_scanhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_scanhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_scanhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_scanhint, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back = lv_btn_create(ui_medicineinpanel);
    lv_obj_set_width(ui_back, 130);
    lv_obj_set_height(ui_back, 70);
    lv_obj_set_x(ui_back, 0);
    lv_obj_set_y(ui_back, 85);
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_back, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_dir(ui_back, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_back, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_back, lv_color_hex(0x0090FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_back, lv_color_hex(0x0059B2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_back, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_back, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_back, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_back, lv_color_hex(0x00FFEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backtext = lv_label_create(ui_back);
    lv_obj_set_width(ui_backtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_backtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backtext, "返回");
    lv_obj_set_style_text_font(ui_backtext, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_medicineinpanel);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 270);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_Panel1);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 310);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 70);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_times = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_times, 50);
    lv_obj_set_height(ui_times, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_times, 20);
    lv_obj_set_y(ui_times, -100);
    lv_obj_set_align(ui_times, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_times, true);
    lv_obj_set_style_text_font(ui_times, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amount = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_amount, 50);
    lv_obj_set_height(ui_amount, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_amount, 20);
    lv_obj_set_y(ui_amount, -30);
    lv_obj_set_align(ui_amount, LV_ALIGN_CENTER);
    lv_textarea_set_one_line(ui_amount, true);
    lv_obj_set_style_text_font(ui_amount, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_texttimes = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_texttimes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_texttimes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_texttimes, -5);
    lv_obj_set_y(ui_texttimes, -100);
    lv_obj_set_align(ui_texttimes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_texttimes, "一天   次");
    lv_obj_set_style_text_font(ui_texttimes, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textamount = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_textamount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textamount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textamount, -5);
    lv_obj_set_y(ui_textamount, -30);
    lv_obj_set_align(ui_textamount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textamount, "一次   粒");
    lv_obj_set_style_text_font(ui_textamount, &ui_font_midbig, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_back, ui_event_back, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_times, ui_event_times, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_amount, ui_event_amount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medicineinpanel, ui_event_medicineinpanel, LV_EVENT_ALL, NULL);

}
