// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingsscreen
extern void ui_settingsscreen_screen_init(void);
extern void ui_settingsscreen_screen_destroy(void);
extern void ui_event_settingsscreen(lv_event_t * e);
extern lv_obj_t * ui_settingsscreen;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_voiceswitchtext;
extern void ui_event_voiceswitch(lv_event_t * e);
extern lv_obj_t * ui_voiceswitch;
extern lv_obj_t * ui_volumetext;
extern void ui_event_volumeset(lv_event_t * e);
extern lv_obj_t * ui_volumeset;
extern lv_obj_t * ui_persontext;
extern void ui_event_personchoose(lv_event_t * e);
extern lv_obj_t * ui_personchoose;
extern lv_obj_t * ui_lighttext;
extern void ui_event_lightset(lv_event_t * e);
extern lv_obj_t * ui_lightset;
extern lv_obj_t * ui_lighttimetext;
extern void ui_event_lighttimeset(lv_event_t * e);
extern lv_obj_t * ui_lighttimeset;
extern lv_obj_t * ui_wifibutton;
extern lv_obj_t * ui_wifitext;
extern lv_obj_t * ui_alarmenabletext;
extern void ui_event_alarmenableswitch(lv_event_t * e);
extern lv_obj_t * ui_alarmenableswitch;
extern lv_obj_t * ui_medtimeouttext;
extern void ui_event_medtimeoutset(lv_event_t * e);
extern lv_obj_t * ui_medtimeoutset;
extern lv_obj_t * ui_settext;
extern void ui_event_setbackbutton(lv_event_t * e);
extern lv_obj_t * ui_setbackbutton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

