// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_settingsscreen = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_voiceswitchtext = NULL;
lv_obj_t * ui_voiceswitch = NULL;
lv_obj_t * ui_volumetext = NULL;
lv_obj_t * ui_volumeset = NULL;
lv_obj_t * ui_persontext = NULL;
lv_obj_t * ui_personchoose = NULL;
lv_obj_t * ui_lighttext = NULL;
lv_obj_t * ui_lightset = NULL;
lv_obj_t * ui_lighttimetext = NULL;
lv_obj_t * ui_lighttimeset = NULL;
lv_obj_t * ui_wifibutton = NULL;
lv_obj_t * ui_wifitext = NULL;
lv_obj_t * ui_alarmenabletext = NULL;
lv_obj_t * ui_alarmenableswitch = NULL;
lv_obj_t * ui_medtimeouttext = NULL;
lv_obj_t * ui_medtimeoutset = NULL;
lv_obj_t * ui_settext = NULL;
lv_obj_t * ui_setbackbutton = NULL;
// event funtions
void ui_event_settingsscreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        touch_event_handler(e);
    }
}

void ui_event_voiceswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        voiceset_change(e);
        _ui_state_modify(ui_volumeset, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
        _ui_state_modify(ui_personchoose, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_volumeset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        volume_set(e);
    }
}

void ui_event_personchoose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        person_change(e);
    }
}

void ui_event_lightset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        light_change(e);
    }
}

void ui_event_lighttimeset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        light_time_change(e);
    }
}

void ui_event_alarmenableswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        med_timeout_switch(e);
        _ui_state_modify(ui_medtimeoutset, LV_STATE_DISABLED, _UI_MODIFY_STATE_TOGGLE);
    }
}

void ui_event_medtimeoutset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        med_timeout_change(e);
    }
}

void ui_event_setbackbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_mainscreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 100, &ui_mainscreen_screen_init);
    }
}

// build funtions

void ui_settingsscreen_screen_init(void)
{
    ui_settingsscreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingsscreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingsscreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingsscreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_settingsscreen);
    lv_obj_set_width(ui_Panel3, 480);
    lv_obj_set_height(ui_Panel3, 230);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 20);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);

    ui_voiceswitchtext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_voiceswitchtext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voiceswitchtext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_voiceswitchtext, -190);
    lv_obj_set_y(ui_voiceswitchtext, 60);
    lv_obj_set_align(ui_voiceswitchtext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_voiceswitchtext, "语音");
    lv_obj_set_style_text_font(ui_voiceswitchtext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voiceswitch = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_voiceswitch, 50);
    lv_obj_set_height(ui_voiceswitch, 25);
    lv_obj_set_x(ui_voiceswitch, -110);
    lv_obj_set_y(ui_voiceswitch, 60);
    lv_obj_set_align(ui_voiceswitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_voiceswitch, LV_STATE_CHECKED);       /// States

    ui_volumetext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_volumetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volumetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volumetext, -190);
    lv_obj_set_y(ui_volumetext, 100);
    lv_obj_set_align(ui_volumetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_volumetext, "音量");
    lv_obj_set_style_text_font(ui_volumetext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volumeset = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_volumeset, 0, 10);
    lv_slider_set_value(ui_volumeset, 2, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_volumeset) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_volumeset, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_volumeset, 150);
    lv_obj_set_height(ui_volumeset, 10);
    lv_obj_set_x(ui_volumeset, -66);
    lv_obj_set_y(ui_volumeset, 100);
    lv_obj_set_align(ui_volumeset, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_volumeset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_volumeset, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_volumeset, lv_color_hex(0xB1B1B1), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_volumeset, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_volumeset, lv_color_hex(0xB1B1B1), LV_PART_KNOB | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_volumeset, 255, LV_PART_KNOB | LV_STATE_DISABLED);

    ui_persontext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_persontext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_persontext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_persontext, -190);
    lv_obj_set_y(ui_persontext, 140);
    lv_obj_set_align(ui_persontext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_persontext, "发音人");
    lv_obj_set_style_text_font(ui_persontext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_personchoose = lv_dropdown_create(ui_Panel3);
    lv_dropdown_set_options(ui_personchoose,
                            "晓玲\n尹小坚\n易小强\n田蓓蓓\n唐老鸭\n小燕子\n贝童\n晓可");
    lv_obj_set_width(ui_personchoose, 150);
    lv_obj_set_height(ui_personchoose, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_personchoose, -65);
    lv_obj_set_y(ui_personchoose, 140);
    lv_obj_set_align(ui_personchoose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_personchoose, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_personchoose, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_personchoose, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_personchoose, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_text_font(ui_personchoose, &ui_font_small, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_personchoose), &ui_font_small,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_personchoose), lv_color_hex(0xB1B1B1),
                              LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_personchoose), 255,  LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_personchoose), &ui_font_small,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_personchoose), lv_color_hex(0xB1B1B1),
                              LV_PART_SELECTED | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_personchoose), 255,  LV_PART_SELECTED | LV_STATE_DISABLED);

    ui_lighttext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_lighttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lighttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lighttext, -190);
    lv_obj_set_y(ui_lighttext, 220);
    lv_obj_set_align(ui_lighttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lighttext, "亮度");
    lv_obj_set_style_text_font(ui_lighttext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightset = lv_slider_create(ui_Panel3);
    lv_slider_set_range(ui_lightset, 0, 10000);
    lv_slider_set_value(ui_lightset, 5000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_lightset) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_lightset, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_lightset, 150);
    lv_obj_set_height(ui_lightset, 10);
    lv_obj_set_x(ui_lightset, -66);
    lv_obj_set_y(ui_lightset, 220);
    lv_obj_set_align(ui_lightset, LV_ALIGN_CENTER);

    ui_lighttimetext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_lighttimetext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lighttimetext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lighttimetext, -190);
    lv_obj_set_y(ui_lighttimetext, 300);
    lv_obj_set_align(ui_lighttimetext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lighttimetext, "熄屏时间");
    lv_obj_set_style_text_font(ui_lighttimetext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lighttimeset = lv_roller_create(ui_Panel3);
    lv_roller_set_options(ui_lighttimeset, "10s\n30s\n60s\n5min\n10min\nnever", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_lighttimeset, 2, LV_ANIM_OFF);
    lv_obj_set_height(ui_lighttimeset, 100);
    lv_obj_set_width(ui_lighttimeset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_lighttimeset, -80);
    lv_obj_set_y(ui_lighttimeset, 300);
    lv_obj_set_align(ui_lighttimeset, LV_ALIGN_CENTER);

    ui_wifibutton = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_wifibutton, 100);
    lv_obj_set_height(ui_wifibutton, 50);
    lv_obj_set_x(ui_wifibutton, 150);
    lv_obj_set_y(ui_wifibutton, -70);
    lv_obj_set_align(ui_wifibutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifibutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifibutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifitext = lv_label_create(ui_wifibutton);
    lv_obj_set_width(ui_wifitext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifitext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifitext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifitext, "WLAN");
    lv_obj_set_style_text_font(ui_wifitext, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmenabletext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_alarmenabletext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_alarmenabletext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_alarmenabletext, -190);
    lv_obj_set_y(ui_alarmenabletext, -90);
    lv_obj_set_align(ui_alarmenabletext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_alarmenabletext, "用药提醒");
    lv_obj_set_style_text_font(ui_alarmenabletext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmenableswitch = lv_switch_create(ui_Panel3);
    lv_obj_set_width(ui_alarmenableswitch, 50);
    lv_obj_set_height(ui_alarmenableswitch, 25);
    lv_obj_set_x(ui_alarmenableswitch, -110);
    lv_obj_set_y(ui_alarmenableswitch, -90);
    lv_obj_set_align(ui_alarmenableswitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_alarmenableswitch, LV_STATE_CHECKED);       /// States

    ui_medtimeouttext = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_medtimeouttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_medtimeouttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_medtimeouttext, -190);
    lv_obj_set_y(ui_medtimeouttext, -20);
    lv_obj_set_align(ui_medtimeouttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_medtimeouttext, "用药超时\n  时间");
    lv_obj_set_style_text_font(ui_medtimeouttext, &ui_font_small, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medtimeoutset = lv_roller_create(ui_Panel3);
    lv_roller_set_options(ui_medtimeoutset, "1min\n15min\n30min\n60min\nnever", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_medtimeoutset, 100);
    lv_obj_set_width(ui_medtimeoutset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_medtimeoutset, -80);
    lv_obj_set_y(ui_medtimeoutset, -20);
    lv_obj_set_align(ui_medtimeoutset, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_medtimeoutset, lv_color_hex(0xB1B1B1), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_medtimeoutset, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_bg_color(ui_medtimeoutset, lv_color_hex(0xB1B1B1), LV_PART_SELECTED | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_medtimeoutset, 255, LV_PART_SELECTED | LV_STATE_DISABLED);

    ui_settext = lv_label_create(ui_settingsscreen);
    lv_obj_set_width(ui_settext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settext, 0);
    lv_obj_set_y(ui_settext, -115);
    lv_obj_set_align(ui_settext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settext, "设置");
    lv_obj_set_style_text_font(ui_settext, &ui_font_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setbackbutton = lv_imgbtn_create(ui_settingsscreen);
    lv_imgbtn_set_src(ui_setbackbutton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_back_png, NULL);
    lv_imgbtn_set_src(ui_setbackbutton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_back_png, NULL);
    lv_obj_set_width(ui_setbackbutton, 40);
    lv_obj_set_height(ui_setbackbutton, 30);
    lv_obj_set_x(ui_setbackbutton, -210);
    lv_obj_set_y(ui_setbackbutton, -115);
    lv_obj_set_align(ui_setbackbutton, LV_ALIGN_CENTER);
    lv_obj_set_style_blend_mode(ui_setbackbutton, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_opa(ui_setbackbutton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_voiceswitch, ui_event_voiceswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_volumeset, ui_event_volumeset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_personchoose, ui_event_personchoose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lightset, ui_event_lightset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lighttimeset, ui_event_lighttimeset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmenableswitch, ui_event_alarmenableswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_medtimeoutset, ui_event_medtimeoutset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_setbackbutton, ui_event_setbackbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsscreen, ui_event_settingsscreen, LV_EVENT_ALL, NULL);

}

void ui_settingsscreen_screen_destroy(void)
{
    if(ui_settingsscreen) lv_obj_del(ui_settingsscreen);

    // NULL screen variables
    ui_settingsscreen = NULL;
    ui_Panel3 = NULL;
    ui_voiceswitchtext = NULL;
    ui_voiceswitch = NULL;
    ui_volumetext = NULL;
    ui_volumeset = NULL;
    ui_persontext = NULL;
    ui_personchoose = NULL;
    ui_lighttext = NULL;
    ui_lightset = NULL;
    ui_lighttimetext = NULL;
    ui_lighttimeset = NULL;
    ui_wifibutton = NULL;
    ui_wifitext = NULL;
    ui_alarmenabletext = NULL;
    ui_alarmenableswitch = NULL;
    ui_medtimeouttext = NULL;
    ui_medtimeoutset = NULL;
    ui_settext = NULL;
    ui_setbackbutton = NULL;

}
