################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include src/subdir.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/arm/cortex-m4/subdir.mk
-include rt-thread/libcpu/arm/common/subdir.mk
-include rt-thread/components/net/sal/src/subdir.mk
-include rt-thread/components/net/sal/socket/subdir.mk
-include rt-thread/components/net/sal/impl/subdir.mk
-include rt-thread/components/net/sal/dfs_net/subdir.mk
-include rt-thread/components/net/netdev/src/subdir.mk
-include rt-thread/components/net/lwip/port/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/netif/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/api/subdir.mk
-include rt-thread/components/libc/posix/io/poll/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/compilers/common/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/drivers/wlan/subdir.mk
-include rt-thread/components/drivers/touch/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/sdio/subdir.mk
-include rt-thread/components/drivers/rtc/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/ipc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/drivers/can/subdir.mk
-include rt-thread/components/dfs/dfs_v1/src/subdir.mk
-include rt-thread/components/dfs/dfs_v1/filesystems/elmfat/subdir.mk
-include rt-thread/components/dfs/dfs_v1/filesystems/devfs/subdir.mk
-include ra_gen/subdir.mk
-include ra/tes/dave2d/src/subdir.mk
-include ra/fsp/src/r_ssi/subdir.mk
-include ra/fsp/src/r_spi/subdir.mk
-include ra/fsp/src/r_sdhi/subdir.mk
-include ra/fsp/src/r_sci_uart/subdir.mk
-include ra/fsp/src/r_sci_spi/subdir.mk
-include ra/fsp/src/r_rtc/subdir.mk
-include ra/fsp/src/r_jpeg/subdir.mk
-include ra/fsp/src/r_ioport/subdir.mk
-include ra/fsp/src/r_icu/subdir.mk
-include ra/fsp/src/r_gpt/subdir.mk
-include ra/fsp/src/r_glcdc/subdir.mk
-include ra/fsp/src/r_ether_phy/subdir.mk
-include ra/fsp/src/r_ether/subdir.mk
-include ra/fsp/src/r_dtc/subdir.mk
-include ra/fsp/src/r_drw/subdir.mk
-include ra/fsp/src/r_dmac/subdir.mk
-include ra/fsp/src/r_can/subdir.mk
-include ra/fsp/src/bsp/mcu/all/subdir.mk
-include ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/subdir.mk
-include packages/webclient-v2.2.0/src/subdir.mk
-include packages/rw007-v2.1.0/src/subdir.mk
-include packages/mbedtls-v2.28.1/ports/src/subdir.mk
-include packages/mbedtls-v2.28.1/mbedtls/library/subdir.mk
-include packages/llmchat-latest/ports/subdir.mk
-include packages/llmchat-latest/subdir.mk
-include packages/cJSON-v1.7.17/subdir.mk
-include packages/LVGL-v8.3.11/src/widgets/subdir.mk
-include packages/LVGL-v8.3.11/src/misc/subdir.mk
-include packages/LVGL-v8.3.11/src/hal/subdir.mk
-include packages/LVGL-v8.3.11/src/font/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/win/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/tileview/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/tabview/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/spinner/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/spinbox/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/span/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/msgbox/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/meter/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/menu/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/list/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/led/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/keyboard/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/imgbtn/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/colorwheel/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/chart/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/calendar/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/widgets/animimg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/mono/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/default/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/themes/basic/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/snapshot/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/msg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/monkey/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/imgfont/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/ime/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/gridnav/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/others/fragment/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/tiny_ttf/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/sjpg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/rlottie/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/qrcode/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/png/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/gif/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/fsdrv/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/freetype/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/ffmpeg/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/libs/bmp/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/layouts/grid/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/layouts/flex/subdir.mk
-include packages/LVGL-v8.3.11/src/extra/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/swm341_dma2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/sw/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/stm32_dma2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/sdl/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/renesas/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/nxp/vglite/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/nxp/pxp/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/arm2d/subdir.mk
-include packages/LVGL-v8.3.11/src/draw/subdir.mk
-include packages/LVGL-v8.3.11/src/core/subdir.mk
-include packages/LVGL-v8.3.11/env_support/rt-thread/subdir.mk
-include libraries/HAL_Drivers/subdir.mk
-include board/ports/wifi/subdir.mk
-include board/ports/touch/gt911/src/subdir.mk
-include board/ports/subdir.mk
-include board/lvgl/demo/ui/screens/subdir.mk
-include board/lvgl/demo/ui/images/subdir.mk
-include board/lvgl/demo/ui/fonts/subdir.mk
-include board/lvgl/demo/ui/components/subdir.mk
-include board/lvgl/demo/ui/subdir.mk
-include board/lvgl/demo/subdir.mk
-include board/lvgl/subdir.mk
-include board/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_DEPS)),)
-include $(S_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.hex \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -O3 -ffunction-sections -fdata-sections -Wall  -g -gdwarf-2 -T "D:\RT-ThreadStudio\workspace\hmi-demo3\script\fsp.ld" -Xlinker --gc-sections -L"D:\RT-ThreadStudio\workspace\hmi-demo3\script" -Wl,-Map,"rtthread.map" -Xlinker --cref -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)

rtthread.hex: rtthread.elf
	arm-none-eabi-objcopy -O ihex "rtthread.elf"  "rtthread.hex"

rtthread.siz: rtthread.elf
	arm-none-eabi-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(OBJS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
