################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
board/lvgl/demo \
board/lvgl/demo/ui/components \
board/lvgl/demo/ui/fonts \
board/lvgl/demo/ui/images \
board/lvgl/demo/ui/screens \
board/lvgl/demo/ui \
board/lvgl \
board/ports \
board/ports/touch/gt911/src \
board/ports/wifi \
board \
libraries/HAL_Drivers \
packages/LVGL-v8.3.11/env_support/rt-thread \
packages/LVGL-v8.3.11/src/core \
packages/LVGL-v8.3.11/src/draw/arm2d \
packages/LVGL-v8.3.11/src/draw \
packages/LVGL-v8.3.11/src/draw/nxp/pxp \
packages/LVGL-v8.3.11/src/draw/nxp/vglite \
packages/LVGL-v8.3.11/src/draw/renesas \
packages/LVGL-v8.3.11/src/draw/sdl \
packages/LVGL-v8.3.11/src/draw/stm32_dma2d \
packages/LVGL-v8.3.11/src/draw/sw \
packages/LVGL-v8.3.11/src/draw/swm341_dma2d \
packages/LVGL-v8.3.11/src/extra/layouts/flex \
packages/LVGL-v8.3.11/src/extra/layouts/grid \
packages/LVGL-v8.3.11/src/extra/libs/bmp \
packages/LVGL-v8.3.11/src/extra/libs/ffmpeg \
packages/LVGL-v8.3.11/src/extra/libs/freetype \
packages/LVGL-v8.3.11/src/extra/libs/fsdrv \
packages/LVGL-v8.3.11/src/extra/libs/gif \
packages/LVGL-v8.3.11/src/extra/libs/png \
packages/LVGL-v8.3.11/src/extra/libs/qrcode \
packages/LVGL-v8.3.11/src/extra/libs/rlottie \
packages/LVGL-v8.3.11/src/extra/libs/sjpg \
packages/LVGL-v8.3.11/src/extra/libs/tiny_ttf \
packages/LVGL-v8.3.11/src/extra \
packages/LVGL-v8.3.11/src/extra/others/fragment \
packages/LVGL-v8.3.11/src/extra/others/gridnav \
packages/LVGL-v8.3.11/src/extra/others/ime \
packages/LVGL-v8.3.11/src/extra/others/imgfont \
packages/LVGL-v8.3.11/src/extra/others/monkey \
packages/LVGL-v8.3.11/src/extra/others/msg \
packages/LVGL-v8.3.11/src/extra/others/snapshot \
packages/LVGL-v8.3.11/src/extra/themes/basic \
packages/LVGL-v8.3.11/src/extra/themes/default \
packages/LVGL-v8.3.11/src/extra/themes/mono \
packages/LVGL-v8.3.11/src/extra/widgets/animimg \
packages/LVGL-v8.3.11/src/extra/widgets/calendar \
packages/LVGL-v8.3.11/src/extra/widgets/chart \
packages/LVGL-v8.3.11/src/extra/widgets/colorwheel \
packages/LVGL-v8.3.11/src/extra/widgets/imgbtn \
packages/LVGL-v8.3.11/src/extra/widgets/keyboard \
packages/LVGL-v8.3.11/src/extra/widgets/led \
packages/LVGL-v8.3.11/src/extra/widgets/list \
packages/LVGL-v8.3.11/src/extra/widgets/menu \
packages/LVGL-v8.3.11/src/extra/widgets/meter \
packages/LVGL-v8.3.11/src/extra/widgets/msgbox \
packages/LVGL-v8.3.11/src/extra/widgets/span \
packages/LVGL-v8.3.11/src/extra/widgets/spinbox \
packages/LVGL-v8.3.11/src/extra/widgets/spinner \
packages/LVGL-v8.3.11/src/extra/widgets/tabview \
packages/LVGL-v8.3.11/src/extra/widgets/tileview \
packages/LVGL-v8.3.11/src/extra/widgets/win \
packages/LVGL-v8.3.11/src/font \
packages/LVGL-v8.3.11/src/hal \
packages/LVGL-v8.3.11/src/misc \
packages/LVGL-v8.3.11/src/widgets \
packages/cJSON-v1.7.17 \
packages/llmchat-latest \
packages/llmchat-latest/ports \
packages/mbedtls-v2.28.1/mbedtls/library \
packages/mbedtls-v2.28.1/ports/src \
packages/rw007-v2.1.0/src \
packages/webclient-v2.2.0/src \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/r_can \
ra/fsp/src/r_dmac \
ra/fsp/src/r_drw \
ra/fsp/src/r_dtc \
ra/fsp/src/r_ether \
ra/fsp/src/r_ether_phy \
ra/fsp/src/r_glcdc \
ra/fsp/src/r_gpt \
ra/fsp/src/r_icu \
ra/fsp/src/r_ioport \
ra/fsp/src/r_jpeg \
ra/fsp/src/r_rtc \
ra/fsp/src/r_sci_spi \
ra/fsp/src/r_sci_uart \
ra/fsp/src/r_sdhi \
ra/fsp/src/r_spi \
ra/fsp/src/r_ssi \
ra/tes/dave2d/src \
ra_gen \
rt-thread/components/dfs/dfs_v1/filesystems/devfs \
rt-thread/components/dfs/dfs_v1/filesystems/elmfat \
rt-thread/components/dfs/dfs_v1/src \
rt-thread/components/drivers/can \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/rtc \
rt-thread/components/drivers/sdio \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/touch \
rt-thread/components/drivers/wlan \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/components/libc/posix/io/poll \
rt-thread/components/net/lwip/lwip-2.0.3/src/api \
rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping \
rt-thread/components/net/lwip/lwip-2.0.3/src/core \
rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4 \
rt-thread/components/net/lwip/lwip-2.0.3/src/netif \
rt-thread/components/net/lwip/port \
rt-thread/components/net/netdev/src \
rt-thread/components/net/sal/dfs_net \
rt-thread/components/net/sal/impl \
rt-thread/components/net/sal/socket \
rt-thread/components/net/sal/src \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m4 \
rt-thread/src \
src \

